group: travis_latest
language: python
cache: pip
python:
    - 3.5
    - 3.6
    - 3.7
install:
    - pip install .
    - pip install flake8 pytest pillow torchvision
before_script:
    - nohup redis-server &
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
    - pytest -v --capture=sys
notifications:
    email:
      on_success: change
      on_failure: change
